customhost = "assignmentdb.cdvvcgampsrc.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "12345678"
customdb = "assignment"
custombucket = "cheahchinhong-bucket"
customregion = "us-east-1"
serverurl = "us-east-1"
